CREATE TABLE "empresa" (
  "empresa_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "aseguradora_id" int,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "ruc" varchar(50)
);

CREATE TABLE "aseguradora" (
  "aseguradora_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "correo_contacto" varchar(100),
  "telefono" varchar(20)
);

CREATE TABLE "vehiculo" (
  "vehiculo_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int,
  "placa" varchar(10) UNIQUE NOT NULL,
  "marca" varchar(50),
  "modelo" varchar(50),
  "anio" int,
  "tipo" varchar(20),
  "estado" varchar(20) DEFAULT 'activo'
);

CREATE TABLE "usuario" (
  "usuario_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int,
  "nombre" varchar(100) NOT NULL,
  "correo" varchar(100) UNIQUE NOT NULL,
  "contrasena" text NOT NULL,
  "rol" varchar(20)
);

CREATE TABLE "tipo_incidencia" (
  "tipo_incidencia_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "descripcion" text
);

CREATE TABLE "incidencia" (
  "incidencia_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehiculo_id" int,
  "usuario_id" int,
  "tipo_incidencia_id" int,
  "descripcion" text NOT NULL,
  "prioridad" varchar(10),
  "estado" varchar(20) DEFAULT 'abierta',
  "fecha_reporte" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "latitud" decimal(10,8),
  "longitud" decimal(11,8)
);

CREATE TABLE "historial_incidencia" (
  "historial_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "incidencia_id" int,
  "usuario_id" int,
  "estado" varchar(30),
  "observacion" text,
  "fecha" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "afectado" (
  "afectado_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "incidencia_id" int,
  "nombre" varchar(100),
  "documento_identidad" varchar(20),
  "tipo_tercero" varchar(30),
  "contacto" varchar(100),
  "descripcion_danio" text
);

CREATE TABLE "reporte_aseguradora" (
  "reporte_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "incidencia_id" int,
  "aseguradora_id" int,
  "fecha_envio" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "estado_envio" varchar(20) DEFAULT 'pendiente',
  "asunto" varchar(150),
  "cuerpo" text,
  "observaciones" text
);

CREATE TABLE "evidencia" (
  "evidencia_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "incidencia_id" int,
  "url_archivo" text NOT NULL,
  "tipo_archivo" varchar(20),
  "fecha_subida" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "historial_uso_vehiculo" (
  "historial_uso_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vehiculo_id" int,
  "usuario_id" int,
  "numero_vueltas" int,
  "fecha_inicio" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "fecha_fin" timestamp
);

ALTER TABLE "empresa" ADD FOREIGN KEY ("aseguradora_id") REFERENCES "aseguradora" ("aseguradora_id");

ALTER TABLE "vehiculo" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("empresa_id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("empresa_id");

ALTER TABLE "incidencia" ADD FOREIGN KEY ("vehiculo_id") REFERENCES "vehiculo" ("vehiculo_id");

ALTER TABLE "incidencia" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id");

ALTER TABLE "incidencia" ADD FOREIGN KEY ("tipo_incidencia_id") REFERENCES "tipo_incidencia" ("tipo_incidencia_id");

ALTER TABLE "historial_incidencia" ADD FOREIGN KEY ("incidencia_id") REFERENCES "incidencia" ("incidencia_id");

ALTER TABLE "historial_incidencia" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id");

ALTER TABLE "afectado" ADD FOREIGN KEY ("incidencia_id") REFERENCES "incidencia" ("incidencia_id");

ALTER TABLE "reporte_aseguradora" ADD FOREIGN KEY ("incidencia_id") REFERENCES "incidencia" ("incidencia_id");

ALTER TABLE "reporte_aseguradora" ADD FOREIGN KEY ("aseguradora_id") REFERENCES "aseguradora" ("aseguradora_id");

ALTER TABLE "evidencia" ADD FOREIGN KEY ("incidencia_id") REFERENCES "incidencia" ("incidencia_id");

ALTER TABLE "historial_uso_vehiculo" ADD FOREIGN KEY ("vehiculo_id") REFERENCES "vehiculo" ("vehiculo_id");

ALTER TABLE "historial_uso_vehiculo" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("usuario_id");
